modLoader="javafml"
loaderVersion="[7,)"
license="MIT"

[[mods]]
modId="universal_translator"
version="${version}"
displayName="MC Auto Translation Tool"
displayURL="https://github.com/wuxiangdan96-byte/mc-auto-translation-tool"
authors="我小张7272635"
description='''Client-side automatic translation for server-provided text across Minecraft interfaces.'''

[[mixins]]
config="universal-translator.neoforge.mixins.json"

[[dependencies.universal_translator]]
modId="neoforge"
type="required"
versionRange="[21.5.98,21.6.0)"
ordering="NONE"
side="CLIENT"

[[dependencies.universal_translator]]
modId="minecraft"
type="required"
versionRange="[1.21.5,1.21.6)"
ordering="NONE"
side="CLIENT"
