org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod_version=1.1
maven_group=org.universaltranslator

minecraft_1_21_11_version=1.21.11
yarn_1_21_11_mappings=1.21.11+build.6
loader_1_21_11_version=0.18.1
fabric_api_1_21_11_version=0.141.4+1.21.11
loom_1_21_11_version=1.14.10

minecraft_26_1_version=26.1
loader_26_1_version=0.19.3
fabric_api_26_1_version=0.145.1+26.1
loom_26_1_version=1.17.19
